fixes after testing
alor-broker/astras-mini-app pull request #19
Opened 2024-09-24 10:15 UTC by agushasok

2024-09-30 10:48 UTC, sbelashevskiy requested changes

2024-09-30 10:48 UTC, sbelashevskiy commented on projects/tg-app/public/i18n/environment-services/tg-app-api-errors-service/en.json
> +  "errorTitle": "Something goes wrong"
Почему в настояцем времени когда аналог на русском в прошедшем?
Обычно на англ. это звучит "Something went wrong"

2024-09-30 10:48 UTC, sbelashevskiy commented on projects/tg-app/src/app/authentication/pages/unlock-page/unlock-page.component.html
> +      <p class="m-0">&nbsp;</p>
зачем тут два пустых параграфа?

2024-09-30 10:48 UTC, sbelashevskiy commented on projects/tg-app/src/app/home/components/positions-list/positions-list.component.ts
> +      .subscribe(instrument => {
take(1)

2024-09-30 10:48 UTC, sbelashevskiy commented on projects/tg-app/src/app/home/components/stop-orders-list/stop-orders-list.component.ts
> +            isUpdating: true,
почему isUpdating всегда true? И какой смысл его выставлять уже после того, как запрос выполнился

2024-09-30 10:48 UTC, sbelashevskiy commented on projects/tg-app/src/app/home/pages/home-page/home-page.component.ts
> +    this.isInvestmentIdeasUnauthorizedError = true;
ОТкуда может возникать эта ошибка у авторизованного пользователя?

2024-10-01 14:08 UTC, agushasok commented on projects/tg-app/src/app/authentication/pages/unlock-page/unlock-page.component.html
> +      <p class="m-0">&nbsp;</p>
чтобы клавиатура с кнопками не скакала при показывании ошибки

2024-10-01 14:36 UTC, agushasok commented on projects/tg-app/src/app/home/pages/home-page/home-page.component.ts
> +    this.isInvestmentIdeasUnauthorizedError = true;
бек должен прокидывать запрос дальше на сторонний сервис и использовать захардкоженный (пока что) токен авторизации для того сервиса. И возвращать ошибку, если токен протухнет

2024-10-24 12:44 UTC, merged